services:
  - type: web
    name: generator-postow-api
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
